const projects = [
    { imageUrl: '/yarn-projects/images/bear.jpg',
      alt: 'bear' },
    { imageUrl: '/yarn-projects/images/dolphin.jpg',
      alt: 'dolphin' },
    { imageUrl: '/yarn-projects/images/halloween_bigfoot.jpg',
      alt: 'halloween bigfoot' },
    { imageUrl: '/yarn-projects/images/lion.jpg',
      alt: 'lion' },
    { imageUrl: '/yarn-projects/images/manta_ray.jpeg',
      alt: 'manta ray' },
    { imageUrl: '/yarn-projects/images/monkey.jpg',
      alt: 'monkey' },
    { imageUrl: '/yarn-projects/images/otter.jpg',
      alt: 'otter' },
    { imageUrl: '/yarn-projects/images/pangolin.jpg',
      alt: 'pangolin' },
    { imageUrl: '/yarn-projects/images/peacock.jpg',
      alt: 'peacock' },
    { imageUrl: '/yarn-projects/images/platypus.jpg',
      alt: 'platypus' },
    { imageUrl: '/yarn-projects/images/polar_bear.jpg',
      alt: 'polar bear' },  
    { imageUrl: '/yarn-projects/images/seal.jpg',
      alt: 'seal' },
    { imageUrl: '/yarn-projects/images/squid.jpg',
      alt: 'squid' },
    { imageUrl: '/yarn-projects/images/starfish.jpg',
      alt: 'starfish' },
    { imageUrl: '/yarn-projects/images/tuxedo_sam.jpg',
      alt: 'tuxedo sam' },
] 

export default projects;