const projects = [
    { imageUrl: '/images/bear.jpg',
      alt: 'bear' },
    { imageUrl: '/images/dolphin.jpg',
      alt: 'dolphin' },
    { imageUrl: '/images/halloween_bigfoot.jpg',
      alt: 'halloween bigfoot' },
    { imageUrl: '/images/lion.jpg',
      alt: 'lion' },
    { imageUrl: '/images/manta_ray.jpeg',
      alt: 'manta ray' },
    { imageUrl: '/images/monkey.jpg',
      alt: 'monkey' },
    { imageUrl: '/images/otter.jpg',
      alt: 'otter' },
    { imageUrl: '/images/pangolin.jpg',
      alt: 'pangolin' },
    { imageUrl: '/images/peacock.jpg',
      alt: 'peacock' },
    { imageUrl: '/images/platypus.jpg',
      alt: 'platypus' },
    { imageUrl: '/images/polar_bear.jpg',
      alt: 'polar bear' },  
    { imageUrl: '/images/seal.jpg',
      alt: 'seal' },
    { imageUrl: '/images/squid.jpg',
      alt: 'squid' },
    { imageUrl: '/images/starfish.jpg',
      alt: 'starfish' },
    { imageUrl: '/images/tuxedo_sam.jpg',
      alt: 'tuxedo sam' },
] 

export default projects;